swagger: "2.0"
info:
  title: Calculator Service
  description: HTTP service for multiplying numbers, a goa teaser
  version: ""
host: localhost:8088
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /multiply/:
    get:
      tags:
      - calc
      summary: multiply calc
      operationId: calc#multiply
      parameters:
      - name: type
        in: query
        description: type description
        required: false
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
